language: java
jdk:
- openjdk8
sudo: required
services:
- docker
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
  > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_9023d7762f93_key -iv $encrypted_9023d7762f93_iv -in web3j.asc.enc -out web3j.asc -d
  fi
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew --stacktrace check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew --stacktrace check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew --stacktrace check publish bintrayUpload -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: build release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check assembleShadowDist -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: O8XzjUOga7oQFMvYRFvcK208vSBZ8jvhDL8WNs+4WUB/jgTEesv1lVMCuDQn2T5Q3RQPq964A4MFYBVQkXht+uNGKci925nyeXrsV/vpey88H34ai3skc31AcrVSuyoEmIlpXRlEpxAd+yBp223J4W2Qk71vQ3HKKRzN7Rx7cSSGwuULOuQ0T4fV3t+3hD8IFnzKeiuTGJLJDAF+y1W1lbNINteiksPSBGdhnkfw3NEXBXbZlJj9ZQKrleIVt+Fcu7PCaQh86YVSusHsJ4ZuEt+RsYe+srUbh4Dx3Aun669w/hNyJJmgYXASTUagYf1GSei0KdooX3pK/3EgnJNd+gzoVic/HHMmbfIzOUzx51EwawS0gaGXd5ii5L126OEBXhK+Os12ZcSWGt7sgRPKdWQ3ztyAMcCBtQWxSes2SJotouUz5g3/oFIE4ReVpJ9m/Kibpx71O34GDwFK/KOdKgsPeIQHf3FwI3/7Rh4ZcyGkdOxvk2wqHJQCSEoa81kFvYL+9enjM+w0sN0kqa7W5bunuxVkOfV65sY+IMAshBZWTjvIi/YnRfMKodlq+zhAW039CGWdJLiSRSRpNaNUbS76gNAIDCtCDdxMqnxIor9xWlgyOOCyon1bqCDmPwL7r7KIZTDy9HPeMsbRD+/F9Ap4S6vRJ1/OXZarLSVP7dA=
  - secure: ADHt2e//gBTRgveyNyS3oRJvAdq6xhdL8/CrHWN2zHzKgSqan+xXv03t3RghxKNtTzFAuLRHvvNY9DVzmLQhs4Rrmg3aJ33V+NiuiR6QSosx8i7+YAs9+O17UsFjbr3CU/z1A2XxjVQ8iCkGs4/VzrV7q1aEVDHF1wbJfw/u5lIxp3ByjapyiGss4vyystg7tpkjKidrcpuojg9PIdT23pOylt9dyfHsOFJ1uA2rBmjMdf9sHctjXNDHHgdXY/p8xxlGUni6ViwL5p3X5f8gAwYmvuhu1O16i+dm22rxr9+XKY7x7IPnFktCU+vb5dYcK5D1yCD9v6vlg9hNJiEPIUgziXCKNz4Avuur23IXinjFaSsq9wK7VheobtSbWO+yJ+nV2U0Pkuw1+Mphf9E//LLZsB4mSyUrz7IdXxTBgh+6RRQRLsolFc5OzY+MP2ZbE/n58mzeisvwRCBdYHORdfBMVh8D6eiaGI2o++1SkbpVPjGD2DpSfoDgbma+XT07VdYqwtNS9YQutKbfWKuLv492Agju8ORT+MP90HTDT1Qh5ZhXWWRFWXX1bqlLN+bGtkXLoD7Bcm3kuenOOpPuNQc93NXSlNiTkh8ETCBmUl5ecspx8H/br1nrhAnczbvkW4LNKUiyBB+JPIABUMh13RxOCJHz6kQmskalaDXyww0=
  - secure: Z2coHKt7U1UyYN2A1EnSbKYENhKNz2VWwVh8cDUc7tuHXkxU8C3u6DzSIzYMsxxrke35zowfQMmtNGIwlap/ZV+sKS3dkg8jC1INcOReq9sy9LTaTWSY3B+ND6LMmZYci5HG5g8jqlfWqBwr4+L64FPG+cBEsvL/6cBnWP3PMxDHA3VaSjuuZMxg0rZ/a6gbJBWm8aLl8D8pf557uLKqYxMIvV5aOV6ojcKdSblKBRv9NxqG05GB0MArQSCoHn7Tu6kOeT8LkBs0OuIT/gPMcCo5XnLJl+r4z/OpJXkWeDJ3+SMCq+ol5AjWSOXBhoGB+sLIEeArgoCPrLPZryaGeMsnSsM+0cO57xqTb8Jfm/snEW4eShYLPWFawYDUK5qoIDnDeDzZy3ECnFaaDDZWiiKw/c5QdSIV8I9mcstrVO5cthAe8cqS4OvH2LY1XvkigjeEQdlzaODzM2oSL8UGN3esEvsbpuT9jDbsFge73gwIE7M3tkAg85DBn9KR9ThJSbRcrtD0VA9Rpmd8hnioazuliufg6HLo+AFg1XUOAShAQCSyLLYGQCTkqp9Y3pdDjMVUlUcd1cv5NBcj3S9F0DbD3taPnB8Y1Vx/+/xwT3KZM6PgrxWj7KC1zx1HRUlWfYj8xXG5ae5WaHKi8Pr46teRIcOkEc5zQJbHnxbnlkA=
  - secure: VUEAqc4iZLPrZMBxib+B8kqZQLc4DPnbGrPdJggVN9DAbl5UZsPOfou9Sr+bv8S1oIzuvzxLz54OUeFaV8S3ad1O73p97wIYlZL1MoNbj7+M5FUTED3sDhyiUh0ubEAjS1CqMzykOP4iiEE0fTvGynUjPYKtes6s4xJdidR1rsYCcTb9w+ylDzQ/coMwzOGYHNndU5Q1WPM1p4ANjulizu8sLlBiQJ6wUYeRt/tCurLp55kDrBTf4w6ATvmchrs689hXmp6nQR++d9byW0/EG8EiF56geWep69h5HWVA1CKKkjo1CUYvIr2fpqDIy51Gt4ug+tiHnfmnd75fITTN8KHXF5p/BLViYqZ8UVPr6+mrnF/TArH8TyG55nagz44qrcU22c/IRPf93Txk6IFdikf5lLTf5lHKWOA/cFGzjXkgNg5qvJnZ5Suux1HQ09to5q4yI1hnEM+Mo9nqCi17XuuC7gWF2aFFGrMiAJ/ZuUCbFeiZ3hSK2k2y/dPwc084bfiEYb+A7uoK3I26CMo5hxjPbqfZ+MyDJu0IJfL6GmxpThCWoIbV1T4L+2FHeC1BrJBAc5gWITQbUlDfr1hlII5xMoFcZeJPXX7vkw2BqvQINjVli/0LRhBORPl5m79ZrRxK4SNGin5O6Z8kk3oddIgr3fRA54zAAidcnDlZ/hQ=
  - secure: o4YGhc9y4g3je09ooRNGDscLOV8F64sktyP9UCAOsE+SvLdygR0g48EQd/VEsOoGMDutIqLAuSLwyR+HIP9sPqZ5vvB8WCF+SdA+Y0C6P4YKp0GIb5ksFPtoZujV/b+N0zi+7y1LDn7NvZ+qRxWUWzJF96hAASYtDydH6ZxlxgoJqJ2wymw+zsJAtgYkFecVjAC+px3fdAaVfEvsDsY5mtS9EhSQPxecvVEEfXZicG2Lk380evN/OmvCp1NKpzM7XzarmU8CfBJdlAMAdgDFETi/ss66OeqWB4OrHjAngGPc+lCRea58Aqb97aMskFuMk49//a3+gwYzoDfNRuYh1hXZfYdY8uYuvRXT84FAiZl6H2TAhaQDyPjTVT/VoZI/U5Ul/MJDpYtPtn4KE6dWLy7L8KYzP0fZvnqiyaXHCvBkHywGp8CuPp37yo5Ft9SSGtzlgfXNAIXBLV8SnAgBkRWr3CSApkWU8ESWhbh0RDmJqW3NTjcE6L/inajA0efKYmpZqa47AiWYY0/LWd8ApNf3q8aHCWZKLNyxTfJGGuBRS4kIgEHaji9P5ax3DzBpSZsG86RqoEg0HyhwCXOqr6WmzDEB8EyEJ9TOnduTrstK5zvR8X6aj8LNm2SiDd2cnkHf/KSr/5jdAe3yx1FD7bE1EluYmALckuI1NOf2rUc=
  - secure: mR0pI93B5ZVQFktR6M1EAJRrNWD38tXJZb22akS+goPCvdxKDeuB7nXnFIc3pa5aU0KurPllaGmUKP7Xwih9tdt5KPvKb3T8ditDV4Hn7OnVv+9YAiP2ewpBZBH8ptDiHObnTTWDRoNqVfAr4FSLf1h2l5G0g7dhrjbIb8Iu8d6o7aJRpAKRBR49T/9RF7x5EjIouiezk5P54g5EwPiC8OBik4+Sjv55a9wizEhDI9X5dKzRCCRVvKyIuax/YmJE0yRtFergr+C0KWajcIIa8Bg5gXJfarIW838Wz4NnaF1wjzeNFavB9Sh8prbzrvFxZvPoC9sK5V/7SG0w7IZ1RT+86TIdPUCCFBbquzj2KaJ5zQV1ADKWC/0siUpUNiR3hn17DXEVVxawHDsAHj4LnfdCu8Q0oqa4qnw6G4rJU1SXynmIMIh8Z/ahfEtMQGgCUm5D5KkncJNu0j5PcpD2KuP5V2lHperLEF0tuWqc0c/JLh4bDzSD3uTsczmT008aByqVh2YSzih9OvA7fivLas5gUZ5CoiTt/vULK89bldW2vqp9RjVDfU8wWOIIhTpllOqY2lO3VPrgqHGJuR/TdSC0e0vM3DKdpYQAjLxPbobX71Gou7qN8e1brgUKp/tjmEHV3sybfTkI3ky4qQqw30wMe2G0kG7yImc5iXkl/Ww=
